"""add trip type to posts

Revision ID: 054f4b264b26
Revises: 6bc871d945c7
Create Date: 2026-08-14 12:08:27.919035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054f4b264b26'
down_revision: Union[str, Sequence[str], None] = '6bc871d945c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('trip_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'trip_type')
    # ### end Alembic commands ###
