"""add trip dates to posts

Revision ID: b6e10913ff1c
Revises: cea085d5aaef
Create Date: 2026-08-15 15:50:41.078239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e10913ff1c'
down_revision: Union[str, Sequence[str], None] = 'cea085d5aaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('posts', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'end_date')
    op.drop_column('posts', 'start_date')
    # ### end Alembic commands ###
